DROP DATABASE IF EXISTS pocket_doc ;
CREATE DATABASE pocket_doc;
USE pocket_doc;
DROP TABLE IF EXISTS body_regions;
DROP TABLE IF EXISTS specific_regions;
DROP TABLE IF EXISTS causes;

CREATE TABLE body_regions (id INT UNSIGNED NOT NULL PRIMARY KEY,
                           name VARCHAR(250) NOT NULL);

CREATE TABLE specific_regions (id INT UNSIGNED NOT NULL PRIMARY KEY,
                               body_region_id INT UNSIGNED NOT NULL,
                               name VARCHAR(250) NOT NULL,
                               FOREIGN KEY (body_region_id) REFERENCES body_regions(id) ON DELETE CASCADE);

CREATE TABLE causes (id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
                     sbody_region_id INT UNSIGNED NOT NULL,
                     name VARCHAR(250) NOT NULL,
                     classification VARCHAR(50) NOT NULL,
                     FOREIGN KEY (sbody_region_id) REFERENCES specific_regions(id) ON DELETE CASCADE);

INSERT INTO body_regions (id, name)
VALUES (1, "Front Head"),
       (2, "Back Head"),
       (3, "Front Chest"),
       (4, "Back Chest"),
       (5, "Front Abdomen"),
       (6, "Back Abdomen"),
       (7, "Front Shoulder"),
       (8, "Back Shoulder"),
       (9, "Front Elbow"),
       (10, "Back Elbow"),
       (11, "Front Forearm"),
       (12, "Back Forearm"),
       (13, "Front Wrist/Hand"),
       (14, "Back Wrist/Hand"),
       (15, "Front Hip"),
       (16, "Back Hip"),
       (17, "Front Thigh"),
       (18, "Back Thigh"),
       (19, "Front Groin"),
       (20, "Back Butt"),
       (21, "Front Knee/Leg"),
       (22, "Back Knee/Leg"),
       (23, "Front Foot/Ankle"),
       (24, "Back Foot/Ankle");
       
INSERT INTO specific_regions (id, body_region_id, name)
VALUES 
       /* head */
       (1, 1, "Facial/Frontal"),
       (2, 1, "Temporal"),
       (3, 1, "Parietal"),
       (4, 1, "Neck"),
       (5, 2, "Occipital"),
       
       /* chest */
       (6, 3, "Anterior"),
       (7, 4, "Posterior"),
       
       /* abdomen */
       (8, 5, "Top Left"),
       (9, 5, "Middle Left"),
       (10, 5, "Bottom Left"),
       (11, 5, "Top Middle"),
       (12, 5, "Middle Middle"),
       (13, 5, "Bottom middle"),
       (14, 5, "Top Right"),
       (15, 5, "Middle Right"),
       (16, 5, "Bottom Right"),
       (17, 6, "Lower"),
       
       /* shoulder */
       (18, 7, "Lateral"),
       (19, 8, "Posterior"),
       (20, 8, "Anterior"),
       
       /* elbow */
       (21, 9, "Lateral"),
       (22, 10, "Posterior"),
       (23, 10, "Anterior"),
       (24, 10, "Medial"),
       
       /* forearm */
       (25, 11, "Lateral"),
       (26, 11, "Medial"),
       (27, 12, "Posterior"),
       (28, 12, "Anterior"),
       
       /* wrist/hand */
       (29, 13, "Lateral"),
       (30, 13, "Medial"),
       (31, 14, "Posterior"),
       (32, 14, "Anterior"),
       (33, 13, "Fingers"),
       (34, 14, "Fingers"),
       
       /* hip */
       (35, 15, "Deep Hip"),
       (36, 16, "Posterior"),
       (37, 16, "Lateral"),
       (38, 16, "Anterolateral"),
       
       /* thigh */
       (39, 17, "Anterior"),
       (40, 17, "Medial"),
       (41, 18, "Anterolateral"),
       
       /* Groin/Butt */
       (42, 19, "Front Groin"),
       (43, 20, "Back Butt"),
       
       /* Knee/Leg */
       (44, 21, "Anterior"),
       (45, 21, "Anteromedial"),
       (46, 21, "Medial"),
       (47, 22, "Lateral"),
       (48, 22, "Posterior"),
       (49, 22, "Posteromedial Corner"),
       (50, 22, "Posterolateral Corner"),
       
       /* Foot */
       (51, 23, "Sole"),
       (52, 23, "Arch"),
       (53, 23, "Toes"),
       (54, 23, "All"),
       (55, 24, "Lateral"),
       (56, 24, "Medial"),
       (57, 24, "Posterior");
       
       
/* head */
INSERT INTO causes (sbody_region_id, name, classification)
VALUES
       /* Facial/Frontal */
       (1, "Buccinator Trigger Point", "default"),
       (1, "C1 radiculopathy", "default"),
       (1, "C3 radiculopathy", "default"),
       (1, "Cavernous sinus syndrome", "default"),
       (1, "Charlin Syndrome", "default"),
       (1, "Cluster headache", "default"),
       (1, "Cricoarytenoid arthritis", "default"),
       (1, "Digastric Muscle Trigger Point", "default"),
       (1, "Ernest Syndrome", "default"),
       (1, "External nasal neuralgia", "default"),
       (1, "Frontalis Trigger Point", "default"),
       (1, "Geniculate Neuralgia", "default"),
       (1, "Glossopharyngeal neuralgia", "default"),
       (1, "Levator Scapulae Trigger Point", "default"),
       (1, "Masseter Trigger Point", "default"),
       (1, "Medial Pterygoid Trigger", "default"),
       (1, "Middle cranial fossa syndrome", "default"),
       (1, "Middle turbinate squeeze syndrome", "default"),
       (1, "Migraine Headache", "default"),
       (1, "Nasociliaris Nerve Syndrome", "default"),
       (1, "Occipitalis Trigger Point", "default"),
       (1, "Orbital apex syndrome / Superior Orbital Fissure Syndrome", "default"),
       (1, "Orbital syndrome", "default"),
       (1, "Parasellar syndrome", "default"),
       (1, "Petrous apex syndrome", "default"),
       (1, "Platysma Trigger Point", "default"),
       (1, "Semispinalis Capitis Trigger Point", "default"),
       (1, "Sinus of Morgani Syndrome", "default"),
       (1, "Sphenoid sinus syndrome", "default"),
       (1, "Splenius Cervicis Trigger Point", "default"),
       (1, "Sternocleidomastoid Trigger Point", "default"),
       (1, "Suboccipital Trigger Point", "default"),
       (1, "Supraorbital neuralgia", "default"),
       (1, "Temporal arteritis", "extreme"),
       (1, "Temporalis Trigger Point", "default"),
       (1, "Tensor Veli Palatine Syndrome", "default"),
       (1, "Tolosa Hunt Syndrome", "default"),
       (1, "Trapezius Trigger Point", "default"),
       (1, "Zygomaticus Trigger Point", "default"),
       
       
       /* Temporal */
       (2, "Alderman's neuralgia", "default"),
       (2, "Atlantooccipital Arthropathy", "default"),
       (2, "C2 radiculopathy", "default"),
       (2, "C3 radiculopathy", "default"),
       (2, "Cricoarytenoid arthritis", "default"),
       (2, "Digastric Trigger Point", "default"),
       (2, "Eagle's syndrome", "default"),
       (2, "Ernest Syndrome", "default"),
       (2, "Greater Occipital and Lesser Occipital Nerve Neuralgia", "default"),
       (2, "Masseter myotendonitis", "default"),
       (2, "Migraine Headache", "default"),
       (2, "Myringitis", "default"),
       (2, "Occipitalis Trigger Point", "default"),
       (2, "Ramsey hunt Syndrome", "default"),
       (2, "Semispinalis Capitis Trigger Point", "default"),
       (2, "sinus syndrome pain", "default"),
       (2, "Splenius Capitis Trigger Point", "default"),
       (2, "Sternocleidomastoid Trigger Point", "default"),
       (2, "Suboccipital Trigger Point", "default"),
       (2, "Temporal arteritis", "default"),
       (2, "Temporal Tendinitis", "default"),
       (2, "Temporomandibular Joint Dysfunction", "default"),
       (2, "Tension Headache", "default"),
       (2, "Tonic tensor tympani syndrome", "default"),
       (2, "Trapezius Trigger Point", "default"),
       
       /* Parietal */
       (3, "Arnold - Chiari", "default"),
       (3, "C2 radiculopathy", "default"),
       (3, "Clivus syndrome", "default"),
       (3, "Frontalis Trigger Point", "default"),
       (3, "Greater Occipital and Lesser Occipital Nerve Neuralgia", "default"),
       (3, "Semispinalis Capitis Trigger Point", "default"),
       (3, "Splenius Capitis Trigger Point", "default"),
       (3, "Splenius Cervicis Trigger Point", "default"),
       (3, "Sternocleidomastoid Trigger Point", "default"),
       (3, "Suboccipital Trigger Point", "default"),
       (3, "Tension Headache", "default"),
       (3, "Trapezius Trigger Point", "default"),
       
       /* Neck */
       (4, "Acute calcific retropharyngeal tendinitis", "default"),  
       (4, "Cardiac Ischemia", "extreme"),  
       (4, "Carotid/Vertebral Artery Dissection", "extreme"),  
       (4, "Carotydynia", "default"),  
       (4, "Cervical Discopathy", "default"),  
       (4, "C3 radiculopathy", "default"),  
       (4, "C4 Radiculopathy", "default"),  
       (4, "Crowded dens", "default"),  
       (4, "C4-C5, C5-C6, C6-C7 Facet Joint Arthropathy", "default"),  
       (4, "Eagle's syndrome", "default"),  
       (4, "Foramen magnum syndrome", "default"),  
       (4, "Glossopharyngeal neuralgia", "default"),  
       (4, "Grisel syndrome", "default"),  
       (4, "Hamular bursitis", "default"),  
       (4, "Lateral Pterygoid Trigger Point", "default"),  
       (4, "Mumps", "extreme"),  
       (4, "Neck tongue Syndrome", "default"),  
       (4, "Occipitoatlas Joint Arthropathy", "default"),  
       (4, "Omohyoideus pain syndrome", "default"),  
       (4, "Ponticulus Posticus", "default"),  
       (4, "Ramsay Hunt Syndrome", "default"),  
       (4, "Retropharyngeal abscess", "default"),  
       (4, "Sialadenitis", "default"),  
       (4, "Splenius capitis trigger point", "default"),  
       (4, "Sternocleidomastoid trigger point", "default"),  
       (4, "Supraglottits / Epiglottitis", "extreme"),  
       (4, "Temporomandibular Joint Dysfunction", "default"),  
       (4, "Tensor Veli Palatine Syndrome", "default"),  
       (4, "Thyrohyoid syndrome/Hyoid syndrome", "default"),  
       (4, "Trapezius Trigger Point", "default"),  
       
       /* Occipital */
       (5, "Arnold-Chiari Malformation", "default"),
       (5, "Atlanto-occipital Arthropathy", "default"),
       (5, "C3 radiculopathy", "default"),
       (5, "C4 radiculopathy", "default"),
       (5, "Crowded dens", "default"),
       (5, "Digastric Trigger Point", "default"),
       (5, "Foramen magnum syndrome", "default"),
       (5, "Greater Occipital and Lesser Occipital Nerve Neuralgia", "default"),
       (5, "Migraine Headache", "default"),
       (5, "Neck tongue Syndrome", "default"),
       (5, "Occipital condyle syndrome", "default"),
       (5, "Occipital neuralgia", "default"),
       (5, "Occipitalis Trigger Point", "default"),
       (5, "Semispinalis Capitis Trigger Point", "default"),
       (5, "Sternocleidomastoid Trigger Point", "default"),
       (5, "Suboccipital Trigger Point", "default"),
       (5, "Tension Headache", "default");
       
/* chest */
INSERT INTO causes (sbody_region_id, name, classification)
VALUES 
       /* anterior */
       (6, "Costochondritis", "default"),
       (6, "Costosternal joint dysfunction", "default"),
       (6, "Manubriosternal joint", "default"),
       (6, "Myocardial Ischemia", "extreme"),
       (6, "Pectoralis Major Bursitis", "default"),
       (6, "Pectoralis Major Trigger Point", "default"),
       (6, "Pectoralis Minor Trigger Point", "default"),
       (6, "Pericarditis", "extreme"),
       (6, "Pleuritis", "extreme"),
       (6, "Pneumothorax", "extreme"),
       (6, "Precordial catch", "default"),
       (6, "Pulmonary Embolus", "extreme"),
       (6, "Slipping rib", "default"),
       (6, "Sternalis Trigger Point", "default"),
       (6, "Subclavius Trigger Point", "default"),
       (6, "Syringmyelia", "default"),
       (6, "Thoracic Aortic Aneurysm", "extreme"),
       (6, "Tietze syndrome", "default"),
       (6, "Xiphodynia", "default"),
       
       /* posterior */
       (7, "Baastrup’s bursitis", "default"),
       (7, "C5 radiculopathy", "default"),
       (7, "C5-C6 Facet Joint", "default"),
       (7, "C6-C7 Facet Joint", "default"),
       (7, "C7 radiculopathy", "default"),
       (7, "Costochondritis", "default"),
       (7, "Costovertebral Joints", "default"),
       (7, "Elastofibroma dorsi", "default"),
       (7, "Endometriosis", "default"),
       (7, "Gastroesophageal Reflux", "default"),
       (7, "Iliocostalis lumborum Trigger Point", "default"),
       (7, "Iliocostalis thoracis Trigger Point", "default"),
       (7, "Levator Scapulae Trigger Point", "default"),
       (7, "Longissimus thoracis Trigger Point", "default"),
       (7, "Multifidi", "default"),
       (7, "Notalgia Parasthetica", "default"),
       (7, "Scalene Trigger Point", "default"),
       (7, "Scapulocostal syndrome", "default"),
       (7, "Scheuermann&#39;s disease", "default"),
       (7, "Serratus anterior Trigger Point", "default"),
       (7, "Serratus posterior inferior Trigger Point", "default"),
       (7, "Serratus posterior superior Trigger Point", "default"),
       (7, "Subserratus bursitis", "default"),
       (7, "Supreaserratus Bursitis", "default"),
       (7, "Syringmyelia", "default"),
       (7, "Thoracic Facet Joint", "default"),
       (7, "Trapezoid bursitis", "default"),
       (7, "Ureter referred pain", "default");
       
/* abdomen */
INSERT INTO causes (sbody_region_id, name, classification)
VALUES 
              /* Top Left */
       (8, "Biliary Tract Disorder", "default"),
       (8, "Hepatitis", "default"),
       (8, "Fitz-Hughes- Curtis", "default"),
       (8, "RUQ Syndrome", "default"),
       (8, "Budd-Chiari Syndrome", "default"),
       (8, "Basal Pneumonia", "default"),
       (8, "Retrocecal Appendicitis", "extreme"),
       
       /* Middle Left */
       (9, "Kidney Stones", "default"),
       (9, "Kidney Infection", "default"),
       
       /* Bottom Left */
       (10, "Appendicitis", "extreme"),
       (10, "Crohn’s Disease", "default"),
       (10, "Ovarian Cyst", "female"),
       (10, "Ovarian Torsion", "extreme"),
       (10, "Ovarian Remnant Syndrome", "female"),
       (10, "Pregnancy", "female"),
       (10, "Ectopic Pregnancy (Ruptured)", "female"),
       (10, "Pelvic Inflammatory Disease", "female"),
       (10, "Tubo-ovarian abscess", "female"),
       (10, "Mittelschmerz", "female"),
       (10, "Pelvic Congestion Syndrome", "female"),
       
       /* Top Middle */
       (11, "Ulcer Disease", "default"),
       (11, "Pancreatitis", "default"),
       (11, "Myocardial Ischemia", "extreme"),
       (11, "Boerhaave Syndrome", "default"),
       
       /* Middle Middle */
       (12, "Pancreatitis", "default"),
       (12, "Myocardial Ischemia", "extreme"),
       (12, "Early Appendicitis", "extreme"),
       (12, "Small Bowel Obstruction", "extreme"),
       (12, "Abdominal Aortic Aneurysm", "default"),
       
       /* Bottom Middle */
       (13, "Urinary Retention", "default"),
       (13, "Pregnancy", "default"),
       (13, "Cystitis", "default"),
       (13, "Fibroid", "female"),
       (13, "Adenomyosis", "female"),
       (13, "Allen-Masters Syndrome", "female"),
       
       /* Top Right */
       (14, "Splenic Disorder", "default"),
       (14, "Basal Pneumonia", "default"),
       
       /* Middle Right */
       (15, "Kidney Stones", "default"),
       (15, "Kidney Infection", "default"),
       (15, "Nutcracker Syndrome", "default"),
       
       /* Bottom Right */
       (16, "Diverticulitis/Diverticulosis", "default"),
       (16, "Ovarian Cyst", "female"),
       (16, "Ovarian Torsion", "extreme"),
       (16, "Ovarian Remnant Syndrome", "female"),
       (16, "Pregnancy", "female"),
       (16, "Ectopic Pregnancy", "default"),
       (16, "Pelvic Inflammatory Disease", "female"),
       (16, "Tubo-ovarian abscess", "female"),
       (16, "Mittelschmerz", "female"),
       (16, "Pelvic Congestion Syndrome", "female"),
       
       /* lower */
       (17, "Abdominal Aortic Aneurysm", "extreme"),
       (17, "Baastrup’s bursitis", "default"),
       (17, "Baastrup’s Disease", "default"),
       (17, "Bertolottis syndrome", "default"),
       (17, "Cauda Equina Syndrome", "extreme"),
       (17, "Conus Medullaris Syndrome", "extreme"),
       (17, "Ectopic Pregnancy, Ruptured", "extreme"),
       (17, "Endometriosis", "default"),
       (17, "Iliolumbar Ligament sprain", "default"),
       (17, "Kidney Stone", "default"),
       (17, "Lumbar Facet Joint", "default"),
       (17, "Musculoskeletal Sprain/Strain", "default"),
       (17, "Posterior Sacroiliac Ligament sprain", "default"),
       (17, "Sacroiliac Joints", "default"),
       (17, "Sacrotuberous ligament sprain", "default"),
       (17, "Spondylolisthesis", "default"),
       (17, "Unrecognized", "extreme"),
       (17, "Ureter referred pain", "default");
       
/* shoulder */
INSERT INTO causes (sbody_region_id, name, classification)
VALUES
       /* lateral */
       (18, "Acromioclavicular Ganglion", "default"),
       (18, "Acromioclavicular subluxation", "default"),
       (18, "Axillary neuropathy/entrapment", "default"),
       (18, "Bankart injury", "default"),
       (18, "C4 Radiculopathy", "default"),
       (18, "C5 radiculopathy", "default"),
       (18, "C8 radiculopathy", "default"),
       (18, "Cardiac Ischemia", "extreme"),
       (18, "Coracobrachial bursitis", "default"),
       (18, "Deltoid Trigger Point deltoid", "default"),
       (18, "Frozen Shoulder", "default"),
       (18, "Hill-Sachs", "default"),
       (18, "Subscapularis trigger point", "default"),
       (18, "Infraspinatus Trigger Point", "default"),
       (18, "Labrum (SLAP) lesion", "default"),
       (18, "Osteoarthritis", "default"),
       (18, "Posterior glenoid impingement posterior shoulder pain", "default"),
       (18, "Scalene Trigger Point", "default"),
       (18, "Sick Scapula", "default"),
       (18, "Spinal Accessory Nerve", "default"),
       (18, "Splenius Capitis Trigger Point", "default"),
       (18, "Splenius Cervicis", "default"),
       (18, "Subacromial bursitis", "default"),
       (18, "Subdeltoid Bursitis", "default"),
       (18, "Supraspinatus Trigger Point Supraspinatus", "default"),
       (18, "Syringmyelia", "default"),
       (18, "Teres Major Trigger Point", "default"),
       (18, "Tietze syndrome", "default"),

       /* posterior */
       (19, "Axillary neuropathy/entrapment", "default"),
       (19, "Bankart injury", "default"),
       (19, "Biliary Tract Disease", "default"),
       (19, "C5-C6 Facet Joint", "default"),
       (19, "C6-C7 Facet Joint", "default"),
       (19, "Deltoid Trigger Point deltoid..", "default"),
       (19, "Endometriosis", "default"),
       (19, "Frozen Shoulder", "default"),
       (19, "Hepatic Disease", "default"),
       (19, "Hill-Sachs injury", "default"),
       (19, "Infraspinatus Trigger Point", "default"),
       (19, "Internal Impingement", "default"),
       (19, "Labrum (SLAP) lesion", "default"),
       (19, "Levator scapulae trigger point", "default"),
       (19, "Long thoracic nerve neuropathy/entrapment", "default"),
       (19, "Osteoarthritis", "default"),
       (19, "Posterior glenoid impingement posterior shoulder pain", "default"),
       (19, "Quadrilateral Space Syndrome", "default"),
       (19, "Scalene Trigger Point", "default"),
       (19, "Shoulder capsule tear", "default"),
       (19, "Sick Scapula Syndrome", "default"),
       (19, "Spinal Accessory Nerve neuralgia/entrapment", "default"),
       (19, "Subacromial bursitis", "default"),
       (19, "Subscapularis Trigger Point", "default"),
       (19, "Supracapular nerve entrapment", "default"),
       (19, "Supraserratus Bursitis", "default"),
       (19, "Supraspinatus Trigger Point", "default"),
       (19, "Teres Major Trigger Point", "default"),
       (19, "Teres Minor Trigger Point", "default"),
       (19, "Trapezoid bursitis", "default"),
       
       (20, "Acromial apophysiolysis", "default"),
       (20, "Acromioclavicular joint sprain", "default"),
       (20, "Anterior Labral Periosteal Sleeve Avulsion", "default"),
       (20, "Axillary neuropath/entrapment", "default"),
       (20, "Bankart Injury", "default"),
       (20, "Biceps subluxation", "default"),
       (20, "Brachialis Trigger Point", "default"),
       (20, "Bursitis of latissimus dorsi", "default"),
       (20, "Cardiac Ischemia", "extreme"),
       (20, "Coracobrachial bursitis", "default"),
       (20, "Coracobrachialis Trigger Point", "default"),
       (20, "Deltoid Trigger Point deltoid", "default"),
       (20, "Frozen Shoulder", "default"),
       (20, "Humeral Avulsion Glenohumeral Ligament sprain", "default"),
       (20, "Infraspinatus Trigger Point", "default"),
       (20, "Osteoarthritis", "default"),
       (20, "Pectoralis Major Trigger Point Pec major", "default"),
       (20, "Perthes lesion", "default"),
       (20, "Scalene Trigger Point", "default"),
       (20, "Spinal Accessory Nerve", "default"),
       (20, "Subacromial bursitis", "default"),
       (20, "Subclavius Trigger Point", "default"),
       (20, "Subcoracoid bursitis", "default"),
       (20, "Subdeltoid Bursitis", "default"),
       (20, "Supraclavicular Nerve Compression", "default"),
       (20, "Supraspinatus Trigger Point", "default"),
       (20, "Tietze syndrome", "default"),
       (20, "Transverse humeral ligament sprain sprain/rupture", "default");
       
/* elbow */
INSERT INTO causes (sbody_region_id, name, classification)
VALUES
       /* lateral */
       (21, "Anconeus trigger point", "default"),
       (21, "Anterolateral capsule ganglion", "default"),
       (21, "Brachioradialis trigger point", "default"),
       (21, "Bursitis of lateral epicondyle", "default"),
       (21, "Elbow Plica", "default"),
       (21, "Extensor Carpi Radialis Longus Trigger Point", "default"),
       (21, "Lateral (Ulnar) Collateral Ligament sprain Sprain", "default"),
       (21, "Lateral Epicondylosis – Tennis Elbow", "default"),
       (21, "Nursemaid’s Elbow", "default"),
       (21, "Osteochondrosis of the capitellum", "default"),
       (21, "Entrapped Synovial Fold of the humeroradial joint", "default"),
       
       /* posterior */
       (22, "Gout", "default"),
       (22, "Interosseous Bursitis of elbow", "default"),
       (22, "Interosseous membrane sprain", "default"),
       (22, "Olecranon apophyseal injury", "default"),
       (22, "Olecranon impingement", "default"),
       (22, "Posterior Elbow Impingement", "default"),
       (22, "Posterolateral rotatory instability", "default"),
       (22, "Snapping Triceps Syndrome", "default"),
       (22, "Subluxating elbow", "default"),
       (22, "Triceps Bursitis", "default"),
       (22, "Triceps tendinosis", "default"),
       (22, "Valgus Extension Overload", "default"),
       
       /* anterior */
       (23, "Anterior capsule strain", "default"),
       (23, "Biceps tendinosis", "default"),
       (23, "Bicipitioradial Bursitis", "default"),
       (23, "Brachialis tendonitis", "default"),
       (23, "Brachialis Trigger Point", "default"),
       
       /* medial */
       (24, "Bursitis medial epicondyle", "default"),
       (24, "Cardiac Ischemia", "extreme"),
       (24, "Extensor Carpi Ulnaris Trigger Point", "default"),
       (24, "Medial (Radial) Collateral Ligament sprain Sprain", "default"),
       (24, "Medial Epicondylar Apophysitis", "default"),
       (24, "Medial Epicondylosis-Golfer’s Elbow", "default"),
       (24, "Stress Injury of the Proximal Ulna", "default"),
       (24, "Ulnar nerve dislocation", "default");
       
/* forearm */
INSERT INTO causes (sbody_region_id, name, classification)
VALUES
       /* lateral */
       (25, "Abductor digiti minimi trigger point", "default"),
       (25, "Adductor opponens pollicis trigger point", "default"),
       (25, "Brachialis trigger point", "default"),
       (25, "Brachioradialis trigger point", "default"),
       (25, "C5 radiculopathy", "default"),
       (25, "C6 radiculopathy", "default"),
       (25, "C6 radiculopathy", "default"),
       (25, "Dequervains Tenosynovitis", "default"),
       (25, "Extensor Carpi Radialis Longus Trigger Point", "default"),
       (25, "Essex-Lopresti Injury", "default"),
       (25, "Extensor digitorum trigger point", "default"),
       (25, "Flexor digitorum profundus trigger point", "default"),
       (25, "Flexor digitorum superficialis/profundus trigger point", "default"),
       (25, "Fracture", "extreme"),
       (25, "Median neuropathy", "default"),
       (25, "Osteoarthritis", "default"),
       (25, "Posterior Interosseous Nerve Syndrome", "default"),
       (25, "Rheumatoid Arthritis", "default"),
       (25, "Scalene trigger point", "default"),
       (25, "Serratus posterior superior trigger point", "default"),
       (25, "Subclavius trigger point", "default"),
       (25, "Supinator trigger point", "default"),
       (25, "Supraspinatus trigger point", "default"),
       (25, "Teres major trigger point", "default"),
       (25, "Trapezius trigger point", "default"),
       (25, "Tricepr brachii trigger point", "default"),
       
       /* medial */
       (26, "Cardiac Ischemia", "extreme"),
       (26, "Abductor minimi trigger point", "default"),
       (26, "Brachioradialis trigger point", "default"),
       (26, "C8 Radiculopathy", "default"),
       (26, "Cubital Tunnel Syndrome", "default"),
       (26, "Extensor Carpi Ulnaris Trigger Point", "default"),
       (26, "Extensor digitorum trigger point", "default"),
       (26, "Flexor digitorum profundus trigger point", "default"),
       (26, "Flexor digitorum superficialis/profundus trigger point", "default"),
       (26, "Fracture", "extreme"),
       (26, "Latissimus dorsi trigger point", "default"),
       (26, "Osteoarthritis", "default"),
       (26, "Pectoralis major trigger point", "default"),
       (26, "Pectoralis minimus trigger point", "default"),
       (26, "Rheumatoid Arthritis", "default"),
       (26, "Scalene trigger point", "default"),
       (26, "Serratus anterior trigger point", "default"),
       (26, "Serratus posterior superior trigger", "default"),
       (26, "Sternalis", "default"),
       (26, "Supraspinatus trigger point", "default"),
       (26, "Triceps brachii trigger point", "default"),
       (26, "Ulnar Neuropathy / Tunnel of Guyon Syndrome", "default"),
       
       /* posterior */
       (27, "C7 radiculopathy", "default"),
       (27, "Compartment Syndrome", "extreme"),
       (27, "Coracobrachialis Trigger Point", "default"),
       (27, "Extensor Digitorum Trigger Point", "default"),
       (27, "Fracture", "extreme"),
       (27, "Latissimus Dorsi Triger Point", "default"),
       (27, "Osteoarthritis", "default"),
       (27, "Rheumatoid Arthritis", "default"),
       (27, "Scalene Trigger Point", "default"),
       (27, "Serratus Posterior Superior Trigger Point", "default"),
       (27, "Subscapularis Trigger Point", "default"),
       (27, "Subscapularis Trigger Point", "default"),
       (27, "Teres Major Trigger Point", "default"),
       (27, "Triceps Brachii Trigger Point", "default"),
       
       /* anterior */
       (28, "Abductor Digiti Trigger Point  ", "default"),
       (28, "Brachialis Trigger Point", "default"),
       (28, "Compartment Syndrome", "extreme"),
       (28, "Fracture", "extreme"),
       (28, "Osteoarthritis", "default"),
       (28, "Pronator Syndrome", "default"),
       (28, "Rheumatoid Arthritis", "default"),
       (28, "Rheumatoid Arthritis", "default"),
       (28, "Serratus PosterIor Superior Trigger Point", "default"),
       (28, "Subclavius Trigger Point", "default"),
       (28, "Subscapularis Trigger Point", "default"),
       (28, "Supinator Trigger Point", "default");
       
/* wrist */
INSERT INTO causes (sbody_region_id, name, classification)
VALUES
       /* lateral */
       (29, "Aseptic necrosis capitate", "default"),
       (29, "Avascular Necrosis of Scaphoid", "default"),
       (29, "Essex-Lopresti Injury", "default"),
       (29, "Gymnast&#39;s Wrist / Distal Radial Physeal Stress Syndrome", "default"),
       (29, "Intersection Syndrome", "default"),
       (29, "Radial Bursitis", "default"),
       (29, "Tunnel of Guyon Syndrome", "default"),
       (29, "Wartenberg syndrome", "default"),
       
       /* medial */
       (30, "Hamatolunate impingement syndrome", "default"),
       (30, "Hypothenar Hammer Syndrome", "default"),
       (30, "Kienboch disease", "default"),
       (30, "Lunate dislocation", "default"),
       (30, "Lunotriquetral injury", "default"),
       (30, "Pisotriquetral arthritis", "default"),
       (30, "Snapping Extensor Carpi Ulnaris", "default"),
       (30, "Triangular Fibrocartilage (TFC) Injury", "default"),
       (30, "Ulnar Bursitis", "default"),
       (30, "Ulnar impaction syndrome", "default"),
       (30, "Ulnar impingement syndrome", "default"),
       (30, "Ulnar styloid impaction syndrome", "default"),
       (30, "Ulnocarpal impaction syndrome", "default"),
       
       /* posterior */
       (31, "Aseptic necrosis capitate", "default"),
       (31, "Carpal boss", "default"),
       (31, "Carpal Instability", "default"),
       (31, "Distal Intersection Syndrome", "default"),
       (31, "Distal Radioulnar joint injury", "default"),
       (31, "Extensor indicis proprius syndrome", "default"),
       (31, "Ganglion/Growths", "default"),
       (31, "Wartenberg syndrome", "default"),
       
       /* anterior */
       (32, "Aseptic necrosis capitate", "default"),
       (32, "Carpal Instability", "default"),
       (32, "Ganglion/Growths", "default");
       
/* hand */
INSERT INTO causes (sbody_region_id, name, classification)
VALUES
       /* fingers */
       (33, "Gamekeepers thumb", "default"),
       (33, "Tunnel of Guyon Syndrome", "default"),
       (33, "Fracture", "extreme"),
       (33, "Jersey Finger", "default"),
       (33, "Osteoarthritis", "default"),
       (33, "Radial Sagittal Band Tear Dorsal Hood Radius", "default"),
       (33, "Rheumatoid Arthritis", "default"),
       (33, "Subclavius trigger point", "default"),
       (33, "Trigger Finger", "default"),
       
       /* fingers */
       (34, "Gamekeepers thumb", "default"),
       (34, "Tunnel of Guyon Syndrome", "default"),
       (34, "Fracture", "extreme"),
       (34, "Jersey Finger", "default"),
       (34, "Osteoarthritis", "default"),
       (34, "Radial Sagittal Band Tear Dorsal Hood Radius", "default"),
       (34, "Rheumatoid Arthritis", "default"),
       (34, "Subclavius trigger point", "default"),
       (34, "Trigger Finger", "default");
       
/* hip */
INSERT INTO causes (sbody_region_id, name, classification)
VALUES
       /* deep hip */
       (35, "Adhesive Capsulitis", "default"),
       (35, "Avascular Necrosis of Femoral Head", "default"),
       (35, "Dysplasia", "default"),
       (35, "Legg-Calves- Perthes", "default"),
       (35, "Osteoarthritis", "default"),
       (35, "Quadrates lumborum trigger point", "default"),
       (35, "Referred Pain from Sacroiliac", "default"),
       (35, "Slipped Capital Femoral Epiphysis", "extreme"),
       (35, "Synovitis", "default"),
       
       /* posterior */
       (36, "Biceps femoris trigger point", "default"),
       (36, "Coccydynia", "default"),
       (36, "Coccygeal Fracture", "extreme"),
       (36, "Gluteus Maximus Bursitis", "default"),
       (36, "Gluteus Maximus trigger point", "default"),
       (36, "Gluteus Medius trigger point", "default"),
       (36, "Gluteus Minimus trigger point", "default"),
       (36, "Ischial Tuberosity Avulsion Fracture", "extreme"),
       (36, "Levator Ani", "default"),
       (36, "Long posterior interosseous ligament sprain", "default"),
       (36, "Lumbar Facet Joint", "default"),
       (36, "Piriformis trigger point", "default"),
       (36, "Posterior Femoral Cutaneous Neuropathy", "default"),
       (36, "Proctalgia fugax", "default"),
       (36, "Quadratus Lumborum trigger point", "default"),
       (36, "Sacral Stress Fracture", "extreme"),
       (36, "Sacroiliac Joints Arthropathy", "default"),
       (36, "Sacrospinous Ligament sprain", "default"),
       (36, "Sacrotuberous Ligament sprain", "default"),
       (36, "Sciatic neuropathy/entrapment", "default"),
       (36, "Semimembranosus trigger point", "default"),
       (36, "Semitendonosus trigger point", "default"),
       (36, "Soleus Trigger Point", "default"),
       (36, "Sphincter ani muscles", "default"),
       
       
       /* lateral */
       (37, "Adductor longus brevis trigger point", "default"),
       (37, "Compartment Syndrome", "extreme"),
       (37, "Furcal Nerve", "default"),
       (37, "Genitofemoral Neuropathy/Entrapment", "default"),
       (37, "Gluteus medius trigger point", "default"),
       (37, "Greater Trochanter Avulsion Fracture", "extreme"),
       (37, "Hip Osteoarthritis", "default"),
       (37, "Iliac Crest Contusion (Hip Pointer)", "default"),
       (37, "Iliolumbar ligament sprain", "default"),
       (37, "Intermedius trigger point", "default"),
       (37, "L3 radiculopathy", "default"),
       (37, "L4 radiculopathy", "default"),
       (37, "Lateral Femoral Cutaneous Neuropathy", "default"),
       (37, "Lateral Recess Stenosis", "default"),
       (37, "Lesser Trochanter Avulsion Fracture", "extreme"),
       (37, "Lumbar Facet Joint", "default"),
       (37, "Paralabral cyst", "default"),
       (37, "Popliteus trigger point", "default"),
       (37, "Posterior Sacroiliac Ligament sprain", "default"),
       (37, "Rectus femoris trigger point", "default"),
       (37, "Tensor fasciae latae trigger point", "default"),
       (37, "Vastus Lateralis", "default"),
       (37, "Vastus medialis trigger point", "default"),
       
       /* anterolateral */
       (38, "Femoral Neuropathy/Entrapment", "default"),
       (38, "Iliocapsularis strain", "default"),
       (38, "Subacute strain at the femoral insertion of anterior hip capsule", "default");
       
/* thigh */
INSERT INTO causes (sbody_region_id, name, classification)
VALUES
       /* anterior */
       (39, "AIIS Avulsion Fracture", "extreme"),
       (39, "ASIS Avulsion Fracture", "extreme"),
       (39, "Femoral Nerve Neuropathy / Entrapment", "default"),
       (39, "Furcal Nerve", "default"),
       (39, "Intermedius trigger point", "default"),
       (39, "L3 radiculopathy", "default"),
       (39, "L4 radiculopathy", "default"),
       (39, "Lateral Recess Stenosis", "default"),
       (39, "Lateralis trigger point", "default"),
       (39, "Lumbar Facet Joint", "default"),
       (39, "Pectineus trigger point", "default"),
       (39, "Psoas Abscess", "default"),
       (39, "Psoas Impingement", "default"),
       (39, "Rectus femoris trigger point", "default"),
       (39, "Sartorius trigger point", "default"),
       (39, "Tensor of Vastus Medialis strain", "default"),
       (39, "Vastus medialis trigger point", "default"),
       
       /* medial */
       (40, "Adductor magnus trigger point", "default"),
       (40, "Adductor Enthesopathy", "default"),
       (40, "Adductor longus brevis trigger point", "default"),
       (40, "Adductor Tendinitis", "default"),
       (40, "Baseball player Hockey Goalie Syndrome", "default"),
       (40, "Brevis trigger point", "default"),
       (40, "CAUDA EQUINA SYNDROME", "extreme"),
       (40, "CONUS MEDULLARIS Syndrome", "extreme"),
       (40, "Endometriosis", "default"),
       (40, "Funiculitis", "default"),
       (40, "Genitofemoral neuropathy/entrapment", "default"),
       (40, "Gracilis trigger point", "default"),
       (40, "Hip Antero-superior Labral Tear with Avulsion of Rectus Femoris (HALTAR)", "default"),
       (40, "Hydrocele", "default"),
       (40, "Iliohypogastric Neuropathy/Entrapment", "default"),
       (40, "Ilioinguinal Neuropathy/Entrapment", "default"),
       (40, "Iliolumbar ligament sprain", "default"),
       (40, "Incipient hernia, conjoint tendon tear", "default"),
       (40, "Incipient hernia, external oblique aponeurosis tear", "default"),
       (40, "Interstitial Cystitis", "default"),
       (40, "Kidney Stone", "default"),
       (40, "Longus trigger point", "default"),
       (40, "Lumbar Facet Joint", "default"),
       (40, "Obturator Neuropathy/Entrapment", "default"),
       (40, "Orchitis", "default"),
       (40, "Osteitis pubis/pubalgia", "default"),
       (40, "Ovarian Cyst", "default"),
       (40, "Pectineus trigger point", "default"),
       (40, "Prostadynia", "default"),
       (40, "Prostatitis", "default"),
       (40, "Pubic Symphysis Osteoarthritis", "default"),
       (40, "Pudendal neuropathy/entrapment", "default"),
       (40, "Ramus Avulsion Fracture", "extreme"),
       (40, "Round Ligament sprain Entrapment", "default"),
       (40, "Sartorious trigger point", "default"),
       (40, "Sexual / Urinary / Reproductive Infections", "extreme"),
       (40, "Sports Hernia", "default"),
       (40, "Suspensory ligament sprain of penis tear", "default"),
       (40, "Testicular/Ovarian Torsion", "extreme"),
       (40, "Ureter referred pain", "default"),
       (40, "Urethritis", "default"),
       (40, "Urinary Tract Infection", "default"),
       (40, "Varicocele", "default"),
       (40, "Vulvodynia", "default"),
       
       /* anterolateral */
       (41, "Femoral Neuropathy/Entrapment", "default"),
       (41, "Iliocapsularis strain", "default"),
       (41, "Subacute strain at the femoral insertion of anterior hip capsule", "default");
       
/* groin/butt */
INSERT INTO causes (sbody_region_id, name, classification)
VALUES
       /* medial */
       (42, "Adductor magnus trigger point", "default"),
       (42, "Adductor Enthesopathy", "default"),
       (42, "Adductor longus brevis trigger point", "default"),
       (42, "Adductor Tendinitis", "default"),
       (42, "Baseball player Hockey Goalie Syndrome", "default"),
       (42, "Brevis trigger point", "default"),
       (42, "CAUDA EQUINA SYNDROME", "extreme"),
       (42, "CONUS MEDULLARIS Syndrome", "extreme"),
       (42, "Endometriosis", "default"),
       (42, "Funiculitis", "default"),
       (42, "Genitofemoral neuropathy/entrapment", "default"),
       (42, "Gracilis trigger point", "default"),
       (42, "Hip Antero-superior Labral Tear with Avulsion of Rectus Femoris (HALTAR)", "default"),
       (42, "Hydrocele", "default"),
       (42, "Iliohypogastric Neuropathy/Entrapment", "default"),
       (42, "Ilioinguinal Neuropathy/Entrapment", "default"),
       (42, "Iliolumbar ligament sprain", "default"),
       (42, "Incipient hernia, conjoint tendon tear", "default"),
       (42, "Incipient hernia, external oblique aponeurosis tear", "default"),
       (42, "Interstitial Cystitis", "default"),
       (42, "Kidney Stone", "default"),
       (42, "Longus trigger point", "default"),
       (42, "Lumbar Facet Joint", "default"),
       (42, "Obturator Neuropathy/Entrapment", "default"),
       (42, "Orchitis", "default"),
       (42, "Osteitis pubis/pubalgia", "default"),
       (42, "Ovarian Cyst", "default"),
       (42, "Pectineus trigger point", "default"),
       (42, "Prostadynia", "default"),
       (42, "Prostatitis", "default"),
       (42, "Pubic Symphysis Osteoarthritis", "default"),
       (42, "Pudendal neuropathy/entrapment", "default"),
       (42, "Ramus Avulsion Fracture", "extreme"),
       (42, "Round Ligament sprain Entrapment", "default"),
       (42, "Sartorious trigger point", "default"),
       (42, "Sexual / Urinary / Reproductive Infections", "extreme"),
       (42, "Sports Hernia", "default"),
       (42, "Suspensory ligament sprain of penis tear", "default"),
       (42, "Testicular/Ovarian Torsion", "extreme"),
       (42, "Ureter referred pain", "default"),
       (42, "Urethritis", "default"),
       (42, "Urinary Tract Infection", "default"),
       (42, "Varicocele", "default"),
       (42, "Vulvodynia", "default"),
       
       /* posterior */
       (43, "Biceps femoris trigger point", "default"),
       (43, "Coccydynia", "default"),
       (43, "Coccygeal Fracture", "extreme"),
       (43, "Gluteus Maximus Bursitis", "default"),
       (43, "Gluteus Maximus trigger point", "default"),
       (43, "Gluteus Medius trigger point", "default"),
       (43, "Gluteus Minimus trigger point", "default"),
       (43, "Ischial Tuberosity Avulsion Fracture", "extreme"),
       (43, "Levator Ani", "default"),
       (43, "Long posterior interosseous ligament sprain", "default"),
       (43, "Lumbar Facet Joint", "default"),
       (43, "Piriformis trigger point", "default"),
       (43, "Posterior Femoral Cutaneous Neuropathy", "default"),
       (43, "Proctalgia fugax", "default"),
       (43, "Quadratus Lumborum trigger point", "default"),
       (43, "Sacral Stress Fracture", "extreme"),
       (43, "Sacroiliac Joints Arthropathy", "default"),
       (43, "Sacrospinous Ligament sprain", "default"),
       (43, "Sacrotuberous Ligament sprain", "default"),
       (43, "Sciatic neuropathy/entrapment", "default"),
       (43, "Semimembranosus trigger point", "default"),
       (43, "Semitendonosus trigger point", "default"),
       (43, "Soleus Trigger Point", "default"),
       (43, "Sphincter ani muscles", "default");
       
/* knee/leg */
INSERT INTO causes (sbody_region_id, name, classification)
VALUES
       /* anterior */
       (44, "Adductor longus brevis trigger point", "default"),
       (44, "Chondromalacia patella", "default"),
       (44, "Compartment Syndrome", "extreme"),
       (44, "Deep infrapatellar bursitis", "default"),
       (44, "Excessive lateral pressure syndrome", "default"),
       (44, "Extensor Digitorum Longus trigger point", "default"),
       (44, "Fracture", "extreme"),
       (44, "Lateral femoral condyle friction syndrome", "default"),
       (44, "Medial Tibial Stress Syndrome", "default"),
       (44, "Osgood-Schlatter disease", "default"),
       (44, "Patellar Sleeve Avulsion", "children"),
       (44, "Patellar tendonosis", "default"),
       (44, "Prepatellar subfascial bursitisQuadriceps Expansion Syndrome", "default"),
       (44, "Quadriceps Expansion Syndrome", "default"),
       (44, "Sinding-Larsen- Johannson disease", "default"),
       (44, "Stress / Occult Fractures", "extreme"),
       (44, "Subcutaneous prepatellar bursitis", "default"),
       (44, "Subcutaneous tibial tuberosity bursitis", "default"),
       (44, "Subfascial prepatellar bursitis", "default"),
       (44, "Subtendinous prepatellar bursitis", "default"),
       (44, "Superficial infrapatellar bursitis", "default"),
       (44, "Suprapatellar bursitis", "default"),
       (44, "Tibialis Anterior trigger point", "default"),
     
       /* anteromedial */
       (45, "Pes Anserine Bursitis", "default"),
       (45, "Gracilis Trigger Point", "default"),
       
       /* medial */
       (46, "Deep Medial Collateral Ligament Sprain", "default"),
       (46, "Furcal Nerve", "default"),
       (46, "Ganglion of medial knee joint capsule", "default"),
       (46, "Gastrocnemius trigger point", "default"),
       (46, "L4 radiculopathy", "default"),
       (46, "Lateral Recess Stenosis", "default"),
       (46, "Medial bursitis of gastrocnemius", "default"),
       (46, "Medial Patellar Retinaculum Strain", "default"),
       (46, "Medial Patellofemoral ligament sprain", "default"),
       (46, "Pellegrini Steida syndrome", "default"),
       (46, "Posterior Oblique Ligament sprain", "default"),
       (46, "Posteromedial knee friction syndrome", "default"),
       (46, "Saphenous Neuropathy", "default"),
       (46, "Sartorious Trigger Point", "default"),
       (46, "Sinding Larson Johannson Disease", "default"),
       (46, "Superficial Medial Collateral Ligament sprain", "default"),
       (46, "Synovitis", "default"),
       (46, "Tibial lateral collateral bursitis", "default"),
       (46, "Cruciate Ligament Injury", "default"),
       
       /* lateral */
       (47, "Compartment Syndrome", "default"),
       (47, "Extensor Digitorum trigger point ", "default"),
       (47, "Extensor Hallucis Longus trigger point ", "default"),
       (47, "Gastrocnemius trigger point", "default"),
       (47, "Gluteus minimus trigger point", "default"),
       (47, "L5 radiculopathy", "default"),
       (47, "Lateral Recess Stenosis", "default"),
       (47, "Peroneus Brevis trigger point", "default"),
       (47, "Peroneus longus/tertius trigger point", "default"),
       (47, "Peroneus Muscles trigger point", "default"),
       (47, "Posterior Sacroiliac Ligament sprain", "default"),
       (47, "Superficial Fibular Neuropathy/Entrapment", "default"),
       (47, "Fibular collateral ligament sprain and bursitis", "default"),
       (47, "Gastrocnemius trigger point", "default"),
       (47, "Iliotibial Band Syndrome", "default"),
       (47, "Knee capsule injury", "default"),
       (47, "Proximal tibiofibular joint sprain", "default"),
       (47, "Cruciate Ligament Injury", "default"),
       
       /* posterior */
       (48, "Bakers Cyst", "default"),
       (48, "Biceps femoris bursitis", "default"),
       (48, "Biceps femoris trigger point", "default"),
       (48, "Compartment Syndrome", "extreme"),
       (48, "Deep Vein Thrombosis / Phlebitis", "extreme"),
       (48, "Fracture", "extreme"),
       (48, "Gastrocnemius bursitis", "default"),
       (48, "Gastrocnemius trigger point", "default"),
       (48, "Gluteus minimus trigger point", "default"),
       (48, "Interossei trigger point", "default"),
       (48, "Knee capsule tear", "default"),
       (48, "Medial head of gastrocnemius tendonosis", "default"),
       (48, "Plantaris trigger point", "default"),
       (48, "Popliteus bursitis", "default"),
       (48, "Popliteal tendonosis", "default"),
       (48, "Popliteal Trigger Point", "default"),
       (48, "Posterior Sacroiliac Ligament sprain", "default"),
       (48, "Sacrospinous Ligament sprain", "default"),
       (48, "Sacrotuberous Ligament sprain", "default"),
       (48, "Semimembranosus bursitis", "default"),
       (48, "Semimembranosus trigger point", "default"),
       (48, "Semitendonosus trigger point", "default"),
       (48, "Soleus trigger point", "default"),
       (48, "Stress / Occult Fractures", "extreme"),
       (48, "Sural Neuropathy/Entrapment", "default"),
       (48, "Tibialis Posterior trigger point", "default"),
       (48, "Transverse genicular ligament sprain", "default"),
       (48, "Cruciate Ligament Injury", "default"),
       
       /* posteromedial corner */
       (49, "Gastrocnemius trigger point", "default"),
       (49, "Medial head of the gastrocnemius tendonosis", "default"),
       (49, "Oblique popliteal ligament sprain", "default"),
       (49, "Popliteal Trigger Point", "default"),
       (49, "Posterior oblique ligament sprain", "default"),
       (49, "Posterior horn of the medial meniscus tear", "default"),
       (49, "Semimembranosus tendonosis", "default"),
       (49, "Cruciate Ligament Injury", "default"),
       
       /* posterolateral corner */
       (50, "Arcuate ligament sprain", "default"),
       (50, "Biceps Femoris strain", "default"),
       (50, "Coronary ligament sprain", "default"),
       (50, "Fabellar snapping and impingement", "default"),
       (50, "Fabellofibular ligament sprain", "default"),
       (50, "Gastrocnemius trigger point", "default"),
       (50, "Iliotibial Tract Injury", "default"),
       (50, "Lateral Capsule strain / tear", "default"),
       (50, "Lateral Collateral Ligament sprain", "default"),
       (50, "Lateral head of the gastrocnemius strain", "default"),
       (50, "LCL Bursitis", "default"),
       (50, "Meniscopopliteal fascicles strain", "default"),
       (50, "Popliteofibular ligament sprain", "default"),
       (50, "Popliteus tendonosis", "default"),
       (50, "Popliteal Trigger Point", "default"),
       (50, "Cruciate Ligament Injury", "default");
       
/* foot */
INSERT INTO causes (sbody_region_id, name, classification)
VALUES
       /* sole */
       (51, "Lateral Plantar Nerve Neuropathy/Entrapment", "default"),
       (51, "Medial Plantar Neuropathy/Entrapment", "default"),
       (51, "Plantar digital nerves", "default"),
       (51, "Plantar fasciitis", "default"),
       (51, "Plantar plate rupture", "default"),
       (51, "Posterior Tibial Neuropathy/Entrapment", "default"),
       (51, "Sesamoiditis", "default"),
       (51, "Superficial Fibular Neuropathy/Entrapment", "default"),
       
       /* arch */
       (52, "Cuboid Syndrome", "default"),
       (52, "Deep peroneal nerve entrapment", "default"),
       (52, "Diabetic Neuropathy", "default"),
       (52, "Extensor tendinitis/tendinopathy", "default"),
       (52, "Gruberi Bursitis", "default"),
       (52, "Inferior Extensor Retinaculum Injury", "default"),
       (52, "Kohler disease / Avascular Necrosis Navicular", "default"),
       (52, "Lisfranc fracture/dislocation", "extreme"),
       (52, "Subtalar dislocation", "extreme"),
       (52, "Subtalar osteoarthritis", "default"),
       (52, "Talus/Talar Dome/Talar Neck fracture", "extreme"),
       
       /* toes */
       (53, "First metatarsal bursitis", "default"),
       (53, "Forefoot extensor bursitis", "default"),
       (53, "Freiberg infraction", "default"),
       (53, "Ganglion", "default"),
       (53, "Gout", "default"),
       (53, "Inflammatory Arthritis", "default"),
       (53, "Intermetatarsal bursitis", "default"),
       (53, "Joplin’s Neuroma", "default"),
       (53, "Morton’s Neuroma", "default"),
       (53, "Plantar plate disruption", "default"),
       (53, "Turf toe", "default"),
       
       /* all */
       (54, "Abductor Hallucis trigger point", "default"),
       (54, "Diabetic Neuropathy", "default"),
       (54, "Flexor Hallucis Brevis trigger point", "default"),
       (54, "Fracture", "default"),
       (54, "Gout", "default"),
       (54, "Osteoarthritis", "default"),
       (54, "Quadratus Plantae trigger", "default"),
       (54, "Stress / Occult Fractures", "default"),
       
       /* lateral */
       (55, "Anterior Talofibular Ligament sprain", "default"),
       (55, "Anterior tibiofibular ligament sprain", "default"),
       (55, "Anterior tibiotalar impingement", "default"),
       (55, "Anteroinferior tibiofibular ligament sprain", "default"),
       (55, "Calcaneofibular ligament sprain", "default"),
       (55, "High Ankle Sprain / Syndesmosis Injury", "default"),
       (55, "Inferior Peroneal Retinaculum Injury", "default"),
       (55, "Intermittent Peroneal Tendon Dislocation", "default"),
       (55, "L5 radiculopathy", "default"),
       (55, "Lateral Calcaneal Neuropathy/Entrapment", "default"),
       (55, "Lateral malleolus bursitis", "default"),
       (55, "Lateral plantar neuropathy/entrapment", "default"),
       (55, "Lateral Recess Stenosis", "default"),
       (55, "Maisonneuve fracture", "default"),
       (55, "S1 radiculopathy", "default"),
       (55, "Sinus tarsi syndrome", "default"),
       
       /* medial */
       (56, "Medial Calcaneal Neuropathy/Entrapment", "default"),
       (56, "Medial Malleolus Bursitis", "default"),
       (56, "Posterior tibial tendon dysfunction", "default"),
       (56, "Sustentaculum tali fracture", "default"),
       
       /* posterior */
       (57, "Achilles Enthesopathy", "default"),
       (57, "Achilles Paratenonitis", "default"),
       (57, "Achilles tendon tear", "default"),
       (57, "Calcaneal Apophysitis (Severs disease)", "default"),
       (57, "Calcaneal stress fracture", "default"),
       (57, "Insertional Achilles Tendinopathy", "default"),
       (57, "Lateral Calcaneal Neuropathy/Entrapment", "default"),
       (57, "Posterior Retinaculum Injury", "default"),
       (57, "Posterosuperior Calcaneal Exostosis", "default"),
       (57, "Retro Achilles Bursitis", "default"),
       (57, "Retrocalcaneal Bursitis", "default"),
       (57, "Subcutaneous calcaneal bursitis", "default");
